"""
registry.py — Dimension registry with HyDE-native embeddings.

Manages the dimension_registry table: registration, similarity-based
resolution, and the topic coverage scaffold used by the planner prompt.

Each research dimension is represented as the centroid of N HyDE
(Hypothetical Document Embedding) abstracts generated by the planner LLM.
New dimension candidates are compared against the registry centroid and
merged if cosine similarity exceeds the resolution threshold (default 0.88).

Public API:
    compute_dim_id(canonical_name, topic) -> str
    generate_hyde_abstract(dimension_name, topic, ollama_client) -> str
    embed_hyde_abstract(abstract_text) -> np.ndarray
    register_dimension(canonical_name, topic, ollama_client, conn, n_abstracts) -> str
    resolve_or_register(candidate_str, topic, ollama_client, conn, threshold, n_abstracts) -> str
    get_all_registry_embeddings(conn) -> list[tuple[str, np.ndarray]]
    get_registry_size(conn) -> int
    get_all_registry_dims_for_prompt(topic, conn) -> list[dict]
    get_dimension_axis_tags(dim_id, topic, conn) -> dict
    generate_topic_scaffold(topic, ollama_client, conn) -> dict
    update_registry_embedding(dim_id, conn) -> None  [stub]
"""

import hashlib
import json
import logging
import re
from datetime import date as _date
from typing import TYPE_CHECKING

import numpy as np

from redpill.dedup import compute_embedding
from redpill.state import deserialize_embedding, serialize_embedding

if TYPE_CHECKING:
    import sqlite3

    from redpill.summarize import PlannerLLMClient

logger = logging.getLogger(__name__)

_HYDE_SYSTEM_PROMPT = (
    "You are a research writing assistant. "
    "Return only the abstract text — no title, no author list, no preamble."
)

_SCAFFOLD_SYSTEM_PROMPT = (
    "You are a research analyst. You return only valid JSON — no explanation, "
    "no markdown, no preamble."
)

# Strip common LLM preambles before storing the abstract text.
_PREAMBLE_RE = re.compile(
    r"^(?:abstract:?\s*|here is[^\n.]*[.\n]\s*|certainly[^\n.]*[.\n]\s*|sure[^\n.]*[.\n]\s*)",
    re.IGNORECASE,
)

_MAX_HYDE_TOKENS = 250


# ---------------------------------------------------------------------------
# dim_id hashing — single source of truth for the entire codebase
# ---------------------------------------------------------------------------


def compute_dim_id(canonical_name: str, topic: str) -> str:
    """Return a stable dim_id for a named dimension within a topic.

    Uses lowercased, stripped inputs with '|' separator to prevent hash
    collisions and ensure case-insensitive identity.

    Format: "dim_" + first 12 hex chars of SHA-256(name|topic).

    Note: the formula used before registry.py was introduced lacked the
    separator and lowercasing. Old rows produced by that formula will not
    match new rows; they age out naturally as the registry fills in.
    """
    raw = (
        canonical_name.lower().strip() + "|" + topic.lower().strip()
    ).encode("utf-8")
    return "dim_" + hashlib.sha256(raw).hexdigest()[:12]


# ---------------------------------------------------------------------------
# HyDE abstract generation and embedding
# ---------------------------------------------------------------------------


def generate_hyde_abstract(
    dimension_name: str,
    topic: str,
    ollama_client: "PlannerLLMClient",
) -> str:
    """Call the planner LLM to produce a ~150-word hypothetical abstract.

    Uses think_override=False and json_format=False because the output is
    free text, not JSON, and thinking overhead is wasteful here.

    Raises RuntimeError on LLM failure — do not swallow. A bad embedding
    is worse than no embedding.
    """
    prompt = (
        "Write a 150-word abstract for a research paper that represents the kind of\n"
        'work covered by the research dimension "' + dimension_name + '" within the\n'
        'broader topic of "' + topic + '".\n\n'
        "The abstract should follow this structure:\n"
        "- Problem: what challenge or gap the work addresses\n"
        "- Method: the approach or technique used\n"
        "- Evaluation: how the work is measured or validated\n"
        "- Domain: the application area or field\n\n"
        "Constraints:\n"
        "- Do not cite or reference specific existing papers\n"
        "- Do not invent specific numeric results (e.g. no '94.3% accuracy')\n"
        "- Use concrete, domain-specific vocabulary — methods, datasets, metrics\n"
        "  that would plausibly appear in papers on this dimension\n"
        "- Write in third person, present tense, as if describing the paper's contribution\n\n"
        "Return only the abstract text. No title, no author list, no preamble."
    )
    raw = ollama_client.generate(
        prompt,
        system=_HYDE_SYSTEM_PROMPT,
        think_override=False,
        json_format=False,
    )
    text = _PREAMBLE_RE.sub("", raw.strip()).strip()
    return text


def embed_hyde_abstract(abstract_text: str) -> np.ndarray:
    """Embed a HyDE abstract using the all-MiniLM-L6-v2 singleton.

    Truncates to 250 whitespace-delimited tokens before encoding.
    Returns an L2-normalized float32 numpy array.
    """
    tokens = abstract_text.split()
    if len(tokens) > _MAX_HYDE_TOKENS:
        abstract_text = " ".join(tokens[:_MAX_HYDE_TOKENS])

    arr = compute_embedding(abstract_text)
    norm = np.linalg.norm(arr)
    if norm == 0.0:
        return arr
    return (arr / norm).astype(np.float32)


# ---------------------------------------------------------------------------
# Registry CRUD
# ---------------------------------------------------------------------------


def register_dimension(
    canonical_name: str,
    topic: str,
    ollama_client: "PlannerLLMClient",
    conn: "sqlite3.Connection",
    n_abstracts: int = 3,
) -> str:
    """Generate n_abstracts HyDE abstracts, average their embeddings, and
    INSERT OR IGNORE the centroid into dimension_registry.

    Returns dim_id. Raises RuntimeError if any abstract generation fails —
    a partial average would silently corrupt the centroid.
    """
    embeddings: list[np.ndarray] = []
    abstracts: list[str] = []

    for i in range(n_abstracts):
        abstract = generate_hyde_abstract(canonical_name, topic, ollama_client)
        abstracts.append(abstract)
        emb = embed_hyde_abstract(abstract)
        embeddings.append(emb)
        logger.debug(
            "register_dimension: abstract %d/%d for %r (%d chars)",
            i + 1,
            n_abstracts,
            canonical_name,
            len(abstract),
        )

    centroid = np.mean(np.stack(embeddings), axis=0)
    norm = np.linalg.norm(centroid)
    if norm > 0.0:
        centroid = centroid / norm
    centroid = centroid.astype(np.float32)

    dim_id = compute_dim_id(canonical_name, topic)
    blob = serialize_embedding(centroid)

    conn.execute(
        """
        INSERT OR IGNORE INTO dimension_registry
            (dim_id, canonical_name, topic, embedding, hyde_abstract,
             pool, alpha, beta, run_count)
        VALUES (?, ?, ?, ?, ?, 'explore', 1, 1, 0)
        """,
        (dim_id, canonical_name, topic, blob, abstracts[0]),
    )
    logger.info(
        "register_dimension: %r → %s (INSERT OR IGNORE)", canonical_name, dim_id
    )
    return dim_id


def resolve_or_register(
    candidate_str: str,
    topic: str,
    ollama_client: "PlannerLLMClient",
    conn: "sqlite3.Connection",
    threshold: float = 0.88,
    n_abstracts: int = 3,
) -> str:
    """Resolve candidate_str to an existing dim_id or register it as new.

    Generates a single HyDE abstract for the similarity probe (resolution
    doesn't need a centroid — one sample is enough to locate it in space).
    If cosine similarity to the closest registry entry exceeds threshold,
    returns that dim_id. Otherwise registers a new dimension with n_abstracts.

    Returns dim_id in both cases.
    """
    abstract = generate_hyde_abstract(candidate_str, topic, ollama_client)
    query_vec = embed_hyde_abstract(abstract)

    registry = get_all_registry_embeddings(conn)

    best_id: str | None = None
    best_sim: float = -1.0

    for dim_id, vec in registry:
        sim = float(np.dot(query_vec, vec))
        if sim > best_sim:
            best_sim = sim
            best_id = dim_id

    decision = "resolved" if (best_id is not None and best_sim > threshold) else "new"
    logger.debug(
        "resolve_or_register: candidate=%r similarity=%.4f → %s dim_id=%r",
        candidate_str,
        best_sim,
        decision,
        best_id,
    )

    if best_id is not None and best_sim > threshold:
        return best_id

    return register_dimension(
        candidate_str, topic, ollama_client, conn, n_abstracts=n_abstracts
    )


def get_all_registry_embeddings(
    conn: "sqlite3.Connection",
) -> list[tuple[str, np.ndarray]]:
    """Return (dim_id, embedding) pairs from dimension_registry.

    Excludes the system sentinels (dim_fallback, dim_base) and rows with
    NULL embedding.
    """
    rows = conn.execute(
        """
        SELECT dim_id, embedding FROM dimension_registry
        WHERE embedding IS NOT NULL
          AND dim_id NOT IN ('dim_fallback', 'dim_base')
        """
    ).fetchall()

    result: list[tuple[str, np.ndarray]] = []
    for row in rows:
        try:
            arr = deserialize_embedding(row["embedding"])
            result.append((row["dim_id"], arr))
        except Exception as exc:
            logger.warning(
                "get_all_registry_embeddings: failed to deserialize dim_id=%r: %s",
                row["dim_id"],
                exc,
            )
    return result


def get_registry_size(conn: "sqlite3.Connection") -> int:
    """Return count of non-system rows in dimension_registry."""
    row = conn.execute(
        """
        SELECT COUNT(*) FROM dimension_registry
        WHERE dim_id NOT IN ('dim_fallback', 'dim_base')
        """
    ).fetchone()
    return row[0] if row else 0


# ---------------------------------------------------------------------------
# Axis tags and coverage map helpers
# ---------------------------------------------------------------------------


def _run_count_to_coverage(run_count: int) -> str:
    if run_count < 3:
        return "sparse"
    if run_count <= 8:
        return "moderate"
    return "high"


def get_dimension_axis_tags(
    dim_id: str,
    topic: str,
    conn: "sqlite3.Connection",
) -> dict:
    """Return axis tags for a registered dimension.

    Joins extracted_terms with seen_items on URL to find terms attributed
    to this dimension via seen_items.dim_id. Falls back gracefully when
    seen_items.dim_id is NULL (rows ingested before dim_id plumbing).

    Returns dict with keys: primary_axis (str), tags (list[str]), coverage (str).
    """
    rows = conn.execute(
        """
        SELECT et.category, et.term, COUNT(*) AS freq
        FROM extracted_terms et
        JOIN seen_items si ON et.source_url = si.url
        WHERE si.dim_id = ? AND et.topic = ?
        GROUP BY et.category, et.term
        ORDER BY freq DESC
        LIMIT 20
        """,
        (dim_id, topic),
    ).fetchall()

    reg_row = conn.execute(
        "SELECT run_count FROM dimension_registry WHERE dim_id = ?", (dim_id,)
    ).fetchone()
    run_count = reg_row["run_count"] if reg_row else 0
    coverage = _run_count_to_coverage(run_count)

    if not rows:
        return {"primary_axis": "unknown", "tags": [], "coverage": coverage}

    category_counts: dict[str, int] = {}
    all_terms: list[str] = []
    for row in rows:
        cat = row["category"] or "unknown"
        category_counts[cat] = category_counts.get(cat, 0) + row["freq"]
        all_terms.append(row["term"])

    primary_axis = max(category_counts, key=category_counts.__getitem__)
    return {
        "primary_axis": primary_axis,
        "tags": all_terms[:3],
        "coverage": coverage,
    }


def get_all_registry_dims_for_prompt(
    topic: str,
    conn: "sqlite3.Connection",
) -> list[dict]:
    """Return all registered dimensions for a topic with axis annotations.

    Used by _build_decompose_prompt to construct the coverage map section.
    Each entry has: dim_id, canonical_name, run_count, primary_axis, tags, coverage.
    """
    rows = conn.execute(
        """
        SELECT dim_id, canonical_name, run_count
        FROM dimension_registry
        WHERE dim_id NOT IN ('dim_fallback', 'dim_base')
          AND topic = ?
        ORDER BY run_count DESC
        """,
        (topic,),
    ).fetchall()

    result: list[dict] = []
    for row in rows:
        axis_info = get_dimension_axis_tags(row["dim_id"], topic, conn)
        result.append(
            {
                "dim_id": row["dim_id"],
                "canonical_name": row["canonical_name"],
                "run_count": row["run_count"],
                **axis_info,
            }
        )
    return result


# ---------------------------------------------------------------------------
# Topic scaffold
# ---------------------------------------------------------------------------


def generate_topic_scaffold(
    topic: str,
    ollama_client: "PlannerLLMClient",
    conn: "sqlite3.Connection",
) -> dict:
    """Generate or return cached topic coverage scaffold.

    Checks topic_scaffold table first. If present, returns the cached dict
    without calling the LLM. If absent, calls the planner LLM (think=True,
    json_format=True) and stores the result with INSERT OR REPLACE.

    The scaffold decomposes the topic into five axes — methodological, domain,
    evaluation, theoretical, application — each listing 4-8 concrete families.
    """
    from redpill.llm_utils import extract_json

    row = conn.execute(
        "SELECT scaffold FROM topic_scaffold WHERE topic = ?", (topic,)
    ).fetchone()

    if row is not None:
        try:
            scaffold = json.loads(row["scaffold"])
            logger.debug(
                "generate_topic_scaffold: returning cached scaffold for %r", topic
            )
            return scaffold
        except json.JSONDecodeError as exc:
            logger.warning(
                "generate_topic_scaffold: cached scaffold is invalid JSON (%s) — regenerating",
                exc,
            )

    prompt = (
        'You are analyzing the research topic: "' + topic + '"\n\n'
        "Decompose this topic into major coverage axes. For each axis, list the\n"
        "primary families, paradigms, or communities that exist within it.\n\n"
        "Return a JSON object with exactly these five keys:\n"
        '- "methodological": technique families and algorithmic approaches\n'
        '- "domain": application areas and scientific fields\n'
        '- "evaluation": evaluation paradigms and benchmark types\n'
        '- "theoretical": theoretical angles and formal frameworks\n'
        '- "application": downstream applications and deployment contexts\n\n'
        "Each value is a list of 4-8 specific, concrete entries.\n"
        "Return only the JSON object."
    )

    raw = ollama_client.generate(prompt, system=_SCAFFOLD_SYSTEM_PROMPT)
    parsed = extract_json(raw)

    _SCAFFOLD_KEYS = ("methodological", "domain", "evaluation", "theoretical", "application")

    if not isinstance(parsed, dict):
        logger.warning(
            "generate_topic_scaffold: LLM returned non-dict (%s) — using empty scaffold",
            type(parsed).__name__,
        )
        parsed = {k: [] for k in _SCAFFOLD_KEYS}

    # Ensure all five keys exist with list values.
    for key in _SCAFFOLD_KEYS:
        if key not in parsed or not isinstance(parsed[key], list):
            parsed[key] = []

    scaffold_json = json.dumps(parsed, ensure_ascii=False)
    today = _date.today().isoformat()
    conn.execute(
        """
        INSERT OR REPLACE INTO topic_scaffold (topic, scaffold, created_at)
        VALUES (?, ?, ?)
        """,
        (topic, scaffold_json, today),
    )
    logger.info("generate_topic_scaffold: generated and stored scaffold for %r", topic)
    return parsed


# ---------------------------------------------------------------------------
# Stub
# ---------------------------------------------------------------------------


def update_registry_embedding(
    dim_id: str,
    conn: "sqlite3.Connection",
) -> None:
    """Stub. Blended embedding update — not called until Step 8."""
    logger.debug("update_registry_embedding: stub called for dim_id=%r", dim_id)
